Source/Models/Lobby.cs
using Kurnik.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Kurnik.Models
{
    public class Lobby
    {
        public int ID { get; set; }
        [Display(Name = "Nazwa")]
        public string Name { get; set; }
        [Display(Name = "Prywatny")]
        public bool Private { get; set; }
        public string OwnerID { get; set; }
        public virtual IList<UserParticipationInLobby> UserParticipations { get; set; }
        public virtual User Owner{ get; set; }
    }
}

Source/Models/LobbyViewModel.cs
using Kurnik.Areas.Identity.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kurnik.Models
{
    public class LobbyViewModel
    {
        public IList<User> Users { get; set; }
        public Lobby Lobby { get; set; }
    }
}

Source/Controllers/LobbyController.cs
using Kurnik.Models;
using Kurnik.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Claims;

namespace Kurnik.Controllers
{
    [Authorize]
    public class LobbyController : Controller
    {
        private readonly ILobbyService _service;
        private readonly string currentUserId;

        public LobbyController(ILobbyService service, IHttpContextAccessor httpContextAccessor)
        {
            _service = service;
            currentUserId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }

        public IActionResult Index()
        {
            return View(_service.GetAllPublicOrOwnedLobbies(currentUserId));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(EditLobbyViewModel lobby)
        {
            try
            {
                _service.CreateLobby(currentUserId, lobby.Name, lobby.Private);
            }
            catch (ArgumentOutOfRangeException ex1)
            {
                return NotFound(ex1);
            }
            return RedirectToAction("Index");
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            if (_service.IsUserOwnerOfTheLobby(id, currentUserId))
            {
                return Forbid();
            }
            _service.RemoveLobby(id, currentUserId);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var lobby = _service.GetLobby(id);
            if (lobby == null)
            {
                return NotFound();
            }
            var isUserParticipator = _service.IsUserParticipatorOfTheLobby(id, currentUserId);
            var isUserOwner = _service.IsUserOwnerOfTheLobby(id, currentUserId);
            ViewBag.isOwner = isUserOwner;
            ViewBag.isParticipator = isUserParticipator;
            return View(lobby);
        }

        public IActionResult Edit(int id)
        {
            var lobby = _service.GetLobby(id);
            if(lobby == null)
            {
                return NotFound();
            }
            if (_service.IsUserOwnerOfTheLobby(id, currentUserId))
            {
                return Forbid();
            }
            var viewModel = new EditLobbyViewModel()
            {
                Name = lobby.Name,
                Private = lobby.Private
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(int id, EditLobbyViewModel viewModel)
        {
            if (_service.IsUserOwnerOfTheLobby(id, currentUserId))
            {
                return Forbid();
            }
            _service.EditLobby(id, viewModel.Name, viewModel.Private);
            return RedirectToAction("Details", new { id });
        }

        [HttpPost]
        public IActionResult Join(int id)
        {
            try
            {
                _service.AddUser(id, currentUserId);
            }
            catch (ArgumentOutOfRangeException ex1)
            {
                return NotFound(ex1);
            }
            catch(InvalidOperationException ex2)
            {
                return Conflict(ex2);
            }
            return RedirectToAction("Details", new { id });
        }
		
		[HttpPost]
		public IActionResult AddLobby(string name, bool isPrivate){
			var lobby = _service.CreateLobby(currentUserId, name, isPrivate);
			ViewData["title"] = "Pokój";
            return View(lobby);
		}

        [HttpPost]
        public IActionResult Leave(int id)
        {
            try
            {
                _service.RemoveUser(id, currentUserId);
            }
            catch(InvalidOperationException ex)
            {
                return Conflict(ex);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Remove(int id, string userId)
        {
            try
            {
                if (_service.IsUserOwnerOfTheLobby(id, userId))
                {
                    return Forbid();
                }
                _service.RemoveUser(id, userId);
            }catch(ArgumentOutOfRangeException e1)
            {
                return NotFound(e1);
            }catch(InvalidOperationException e2)
            {
                return Conflict(e2);
            }
            return RedirectToAction("Details", new { id });
        }

        // consume with ajax call
        [HttpPost]
        [Route("/lobbies/{lobbyId}/invitations")]
        public IActionResult InviteUser(int lobbyId, [FromBody] string invitedUserId)
        {
            try
            {
                if (!_service.IsUserOwnerOfTheLobby(lobbyId, currentUserId))
                {
                    return Forbid();
                }
                _service.InviteUser(lobbyId, invitedUserId);
            }catch(ArgumentOutOfRangeException ex1)
            {
                return NotFound(ex1);
            }
            catch (InvalidOperationException ex2)
            {
                return Conflict(ex2);
            }
            return Ok();
        }
    }
}

Source/Views/Lobby/Create.cshtml
@model Kurnik.Models.EditLobbyViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Lobby</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Private" /> @Html.DisplayNameFor(model => model.Private)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Source/Views/Lobby/Details.cshtml
@model Kurnik.Models.Lobby;
<h2>Pokój o id @ViewContext.RouteData.Values["id"]</h2>

<p>
    Nazwa: @Model.Name
</p>
<p>
    Prywatny: @Model.Private
</p>

@if (ViewBag.isOwner)
{
    <a asp-area="" asp-controller="Lobby" asp-action="Edit" asp-route-id="@Model.ID">Edytuj</a>
}
@if (!ViewBag.isParticipator)
{
    <form asp-controller="Lobby" asp-action="Join" asp-route-id="@ViewContext.RouteData.Values["id"]" method="post" role="form">
        <button type="submit">Dołącz</button>
    </form>
}
@if (ViewBag.IsParticipator)
{
    <form asp-controller="Lobby" asp-action="Leave" asp-route-id="@ViewContext.RouteData.Values["id"]"
          method="post" role="form">
        <button type="submit">Wyjdź</button>
    </form>
}

<br />
<br />

<p>
    Użytkownicy:
</p>
@for (var i = 0; i < Model.UserParticipations.Count; i++)
{
    var user = Model.UserParticipations.ElementAt(i).User;
    <text>@user.Email id=@user.Id</text>
    @if (ViewBag.isOwner)
    {
        <form asp-controller="Lobby" asp-action="Remove" asp-route-id="@ViewContext.RouteData.Values["id"]" method="post" role="form">
            <input type="hidden" value="@user.Id" name="userId" />
            <button type="submit">Usuń</button>
        </form>
    }
    <br />
}

<input type="text" id="message-input"/>
<button id="send-message-button">Wyślij</button>

<script src="~/lib/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

Source/Views/Lobby/Edit.cshtml
@model Kurnik.Models.EditLobbyViewModel;

<h2>Ustawienia pokoju o id @ViewContext.RouteData.Values["id"]</h2>

<form asp-controller="Lobby" asp-action="Edit" asp-route-id="@ViewContext.RouteData.Values["id"]"
      method="post" class="form-horizontal" role="form">
    Nazwa: <input asp-for="Name"/> <br/>
    Prywatny <input type="checkbox" asp-for="Private"/> <br/>
    <button type="submit">Zapisz</button>
</form>

Source/Views/Lobby/Index.cshtml
@model IEnumerable<Kurnik.Models.Lobby>

@{
    ViewData["Title"] = "View";
}

<h2>List</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Private)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Private)
            </td>
        </tr>
}
    </tbody>
</table>